local hellokittysouljia = Instance.new("ScreenGui")
hellokittysouljia.Name = "hellokittysouljia"
hellokittysouljia.Parent = game:GetService'CoreGui'
hellokittysouljia.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
hellokittysouljia.ResetOnSpawn = false

local BackFrame = Instance.new("Frame")
BackFrame.Name = "BackFrame"
BackFrame.Parent = hellokittysouljia
BackFrame.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
BackFrame.BorderColor3 = Color3.fromRGB(0, 0, 0)
BackFrame.BorderSizePixel = 0
BackFrame.Position = UDim2.new(0.586021483, 0, 0.111662529, 0)
BackFrame.Size = UDim2.new(0, 482, 0, 579)

local MainFrame = Instance.new("Frame")
MainFrame.Name = "MainFrame"
MainFrame.Parent = BackFrame
MainFrame.BackgroundColor3 = Color3.fromRGB(25, 25, 25)
MainFrame.BorderColor3 = Color3.fromRGB(85, 0, 255)
MainFrame.BorderSizePixel = 2
MainFrame.Position = UDim2.new(0.0103734443, 0, 0.00863557868, 0)
MainFrame.Size = UDim2.new(0, 472, 0, 569)

local ToolBar = Instance.new("Frame")
ToolBar.Name = "ToolBar"
ToolBar.Parent = MainFrame
ToolBar.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
ToolBar.BorderColor3 = Color3.fromRGB(0, 0, 0)
ToolBar.BorderSizePixel = 0
ToolBar.Size = UDim2.new(0, 471, 0, 27)

local CombatButton = Instance.new("TextButton")
CombatButton.Name = "CombatButton"
CombatButton.Parent = ToolBar
CombatButton.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
CombatButton.BackgroundTransparency = 1.000
CombatButton.BorderColor3 = Color3.fromRGB(255, 255, 255)
CombatButton.BorderSizePixel = 0
CombatButton.Position = UDim2.new(0.0127388537, 0, 0, 0)
CombatButton.Size = UDim2.new(0, 55, 0, 27)
CombatButton.Font = Enum.Font.Highway
CombatButton.Text = "Combat"
CombatButton.TextColor3 = Color3.fromRGB(255, 255, 255)
CombatButton.TextSize = 16.000
CombatButton.TextWrapped = true

local MotionButton = Instance.new("TextButton")
MotionButton.Name = "MotionButton"
MotionButton.Parent = ToolBar
MotionButton.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
MotionButton.BackgroundTransparency = 1.000
MotionButton.BorderColor3 = Color3.fromRGB(255, 255, 255)
MotionButton.BorderSizePixel = 0
MotionButton.Position = UDim2.new(0.129511684, 0, 0, 0)
MotionButton.Size = UDim2.new(0, 55, 0, 27)
MotionButton.Font = Enum.Font.Highway
MotionButton.Text = "Motion"
MotionButton.TextColor3 = Color3.fromRGB(255, 255, 255)
MotionButton.TextSize = 16.000
MotionButton.TextWrapped = true

local CFrameButton = Instance.new("TextButton")
CFrameButton.Name = "CFrameButton"
CFrameButton.Parent = ToolBar
CFrameButton.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
CFrameButton.BackgroundTransparency = 1.000
CFrameButton.BorderColor3 = Color3.fromRGB(255, 255, 255)
CFrameButton.BorderSizePixel = 0
CFrameButton.Position = UDim2.new(0.2462845, 0, 0, 0)
CFrameButton.Size = UDim2.new(0, 55, 0, 27)
CFrameButton.Font = Enum.Font.Highway
CFrameButton.Text = "CFrames"
CFrameButton.TextColor3 = Color3.fromRGB(255, 255, 255)
CFrameButton.TextSize = 16.000

local MiscButton = Instance.new("TextButton")
MiscButton.Name = "MiscButton"
MiscButton.Parent = ToolBar
MiscButton.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
MiscButton.BackgroundTransparency = 1.000
MiscButton.BorderColor3 = Color3.fromRGB(255, 255, 255)
MiscButton.BorderSizePixel = 0
MiscButton.Position = UDim2.new(0.363057315, 0, 0, 0)
MiscButton.Size = UDim2.new(0, 55, 0, 27)
MiscButton.Font = Enum.Font.Highway
MiscButton.Text = "Misc"
MiscButton.TextColor3 = Color3.fromRGB(255, 255, 255)
MiscButton.TextSize = 16.000

local UIButton = Instance.new("TextButton")
UIButton.Name = "UIButton"
UIButton.Parent = ToolBar
UIButton.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
UIButton.BackgroundTransparency = 1.000
UIButton.BorderColor3 = Color3.fromRGB(255, 255, 255)
UIButton.BorderSizePixel = 0
UIButton.Position = UDim2.new(0.46072188, 0, 0, 0)
UIButton.Size = UDim2.new(0, 35, 0, 27)
UIButton.Font = Enum.Font.Highway
UIButton.Text = "UI"
UIButton.TextColor3 = Color3.fromRGB(255, 255, 255)
UIButton.TextSize = 16.000

local FileButton = Instance.new("TextButton")
FileButton.Name = "FileButton"
FileButton.Parent = ToolBar
FileButton.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
FileButton.BackgroundTransparency = 1.000
FileButton.BorderColor3 = Color3.fromRGB(255, 255, 255)
FileButton.BorderSizePixel = 0
FileButton.Position = UDim2.new(0.535031855, 0, 0, 0)
FileButton.Size = UDim2.new(0, 35, 0, 27)
FileButton.Font = Enum.Font.Highway
FileButton.Text = "File"
FileButton.TextColor3 = Color3.fromRGB(255, 255, 255)
FileButton.TextSize = 16.000

local LineFrame = Instance.new("Frame")
LineFrame.Name = "LineFrame"
LineFrame.Parent = ToolBar
LineFrame.BackgroundColor3 = Color3.fromRGB(85, 0, 255)
LineFrame.BorderColor3 = Color3.fromRGB(0, 0, 0)
LineFrame.BorderSizePixel = 0
LineFrame.Position = UDim2.new(0, 0, 1, 0)
LineFrame.Size = UDim2.new(0, 471, 0, 2)

local ExitButton = Instance.new("TextButton")
ExitButton.Name = "ExitButton"
ExitButton.Parent = ToolBar
ExitButton.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ExitButton.BackgroundTransparency = 1.000
ExitButton.BorderColor3 = Color3.fromRGB(0, 0, 0)
ExitButton.BorderSizePixel = 0
ExitButton.Position = UDim2.new(0.955413997, 0, 0, 0)
ExitButton.Size = UDim2.new(0, 22, 0, 26)
ExitButton.Font = Enum.Font.Highway
ExitButton.Text = "X"
ExitButton.TextColor3 = Color3.fromRGB(255, 255, 255)
ExitButton.TextSize = 20.000

local MinusButton = Instance.new("TextButton")
MinusButton.Name = "MinusButton"
MinusButton.Parent = ToolBar
MinusButton.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
MinusButton.BackgroundTransparency = 1.000
MinusButton.BorderColor3 = Color3.fromRGB(0, 0, 0)
MinusButton.BorderSizePixel = 0
MinusButton.Position = UDim2.new(0.878980875, 0, 0, 0)
MinusButton.Size = UDim2.new(0, 36, 0, 26)
MinusButton.Font = Enum.Font.Highway
MinusButton.Text = "—"
MinusButton.TextColor3 = Color3.fromRGB(255, 255, 255)
MinusButton.TextSize = 20.000

local Title = Instance.new("TextButton")
Title.Name = "Title"
Title.Parent = ToolBar
Title.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
Title.BackgroundTransparency = 1.000
Title.BorderColor3 = Color3.fromRGB(255, 255, 255)
Title.BorderSizePixel = 0
Title.Position = UDim2.new(0.685774922, 0, 0, 0)
Title.Size = UDim2.new(0, 55, 0, 27)
Title.Font = Enum.Font.Highway
Title.Text = "souljia4ever"
Title.TextColor3 = Color3.fromRGB(255, 255, 255)
Title.TextSize = 16.000

local CombatScrollingFrame1 = Instance.new("ScrollingFrame")
CombatScrollingFrame1.Name = "CombatScrollingFrame1"
CombatScrollingFrame1.Parent = MainFrame
CombatScrollingFrame1.Active = true
CombatScrollingFrame1.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
CombatScrollingFrame1.BorderColor3 = Color3.fromRGB(0, 0, 0)
CombatScrollingFrame1.BorderSizePixel = 0
CombatScrollingFrame1.Position = UDim2.new(0, 0, 0.0509666093, 0)
CombatScrollingFrame1.Size = UDim2.new(0, 236, 0, 540)
CombatScrollingFrame1.ScrollBarThickness = 4

local CamlockFrame = Instance.new("Frame")
CamlockFrame.Name = "CamlockFrame"
CamlockFrame.Parent = CombatScrollingFrame1
CamlockFrame.BackgroundColor3 = Color3.fromRGB(15, 15, 15)
CamlockFrame.BorderColor3 = Color3.fromRGB(0, 0, 0)
CamlockFrame.BorderSizePixel = 0
CamlockFrame.Position = UDim2.new(0.0309999995, 0, 0.00499999989, 0)
CamlockFrame.Size = UDim2.new(0, 221, 0, 170)

local CamlockLabel = Instance.new("TextLabel")
CamlockLabel.Name = "CamlockLabel"
CamlockLabel.Parent = CamlockFrame
CamlockLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
CamlockLabel.BackgroundTransparency = 1.000
CamlockLabel.BorderColor3 = Color3.fromRGB(0, 0, 0)
CamlockLabel.BorderSizePixel = 0
CamlockLabel.Size = UDim2.new(0, 61, 0, 18)
CamlockLabel.Font = Enum.Font.Highway
CamlockLabel.Text = "Camlock"
CamlockLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
CamlockLabel.TextSize = 14.000

local CamlockTargetBox = Instance.new("TextBox")
CamlockTargetBox.Name = "CamlockTargetBox"
CamlockTargetBox.Parent = CamlockFrame
CamlockTargetBox.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
CamlockTargetBox.BorderColor3 = Color3.fromRGB(255, 255, 255)
CamlockTargetBox.BorderSizePixel = 0
CamlockTargetBox.Position = UDim2.new(0.0678733066, 0, 0.400000006, 0)
CamlockTargetBox.Size = UDim2.new(0, 195, 0, 22)
CamlockTargetBox.Font = Enum.Font.Highway
CamlockTargetBox.PlaceholderColor3 = Color3.fromRGB(255, 255, 255)
CamlockTargetBox.PlaceholderText = "Enter Player Username"
CamlockTargetBox.Text = ""
CamlockTargetBox.TextColor3 = Color3.fromRGB(0, 0, 0)
CamlockTargetBox.TextSize = 15.000

local CamlockTargetLabel = Instance.new("TextLabel")
CamlockTargetLabel.Name = "CamlockTargetLabel"
CamlockTargetLabel.Parent = CamlockTargetBox
CamlockTargetLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
CamlockTargetLabel.BackgroundTransparency = 1.000
CamlockTargetLabel.BorderColor3 = Color3.fromRGB(0, 0, 0)
CamlockTargetLabel.BorderSizePixel = 0
CamlockTargetLabel.Position = UDim2.new(0.0696151331, 0, -0.891774952, 0)
CamlockTargetLabel.Size = UDim2.new(0, 168, 0, 15)
CamlockTargetLabel.Font = Enum.Font.Highway
CamlockTargetLabel.Text = "Camlock Target"
CamlockTargetLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
CamlockTargetLabel.TextSize = 14.000

local CamlockPartsButton = Instance.new("TextButton")
CamlockPartsButton.Name = "CamlockPartsButton"
CamlockPartsButton.Parent = CamlockFrame
CamlockPartsButton.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
CamlockPartsButton.BorderColor3 = Color3.fromRGB(0, 0, 0)
CamlockPartsButton.BorderSizePixel = 0
CamlockPartsButton.Position = UDim2.new(0.0588235296, 0, 0.747058809, 0)
CamlockPartsButton.Size = UDim2.new(0, 195, 0, 22)
CamlockPartsButton.Font = Enum.Font.Highway
CamlockPartsButton.Text = "Torso"
CamlockPartsButton.TextColor3 = Color3.fromRGB(255, 255, 255)
CamlockPartsButton.TextSize = 15.000

local CamlockPartsLabel = Instance.new("TextLabel")
CamlockPartsLabel.Name = "CamlockPartsLabel"
CamlockPartsLabel.Parent = CamlockPartsButton
CamlockPartsLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
CamlockPartsLabel.BackgroundTransparency = 1.000
CamlockPartsLabel.BorderColor3 = Color3.fromRGB(0, 0, 0)
CamlockPartsLabel.BorderSizePixel = 0
CamlockPartsLabel.Position = UDim2.new(0.0696151331, 0, -0.891774952, 0)
CamlockPartsLabel.Size = UDim2.new(0, 168, 0, 15)
CamlockPartsLabel.Font = Enum.Font.Highway
CamlockPartsLabel.Text = "Camlock Part"
CamlockPartsLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
CamlockPartsLabel.TextSize = 14.000

local CamlockParts = Instance.new("TextLabel")
CamlockParts.Name = "CamlockParts+"
CamlockParts.Parent = CamlockPartsButton
CamlockParts.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
CamlockParts.BackgroundTransparency = 1.000
CamlockParts.BorderColor3 = Color3.fromRGB(0, 0, 0)
CamlockParts.BorderSizePixel = 0
CamlockParts.Position = UDim2.new(0.856410265, 0, 0.13636364, 0)
CamlockParts.Size = UDim2.new(0, 28, 0, 16)
CamlockParts.Font = Enum.Font.Highway
CamlockParts.Text = "+"
CamlockParts.TextColor3 = Color3.fromRGB(255, 255, 255)
CamlockParts.TextSize = 20.000

local CamlockPartFrame = Instance.new("Frame")
CamlockPartFrame.Name = "CamlockPartFrame"
CamlockPartFrame.Parent = CamlockPartsButton
CamlockPartFrame.BackgroundColor3 = Color3.fromRGB(15, 15, 15)
CamlockPartFrame.BorderColor3 = Color3.fromRGB(0, 0, 0)
CamlockPartFrame.BorderSizePixel = 0
CamlockPartFrame.Position = UDim2.new(0, 0, 1, 0)
CamlockPartFrame.Size = UDim2.new(0, 194, 0, 141)

local CamlockPartHeadButton = Instance.new("TextButton")
CamlockPartHeadButton.Name = "CamlockPartHeadButton"
CamlockPartHeadButton.Parent = CamlockPartFrame
CamlockPartHeadButton.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
CamlockPartHeadButton.BorderColor3 = Color3.fromRGB(0, 0, 0)
CamlockPartHeadButton.BorderSizePixel = 0
CamlockPartHeadButton.Position = UDim2.new(0.0149999997, 0, 0.0500000007, 0)
CamlockPartHeadButton.Size = UDim2.new(0, 188, 0, 22)
CamlockPartHeadButton.Font = Enum.Font.Highway
CamlockPartHeadButton.Text = "Head"
CamlockPartHeadButton.TextColor3 = Color3.fromRGB(255, 255, 255)
CamlockPartHeadButton.TextSize = 15.000

local CamlockPartTorsoButton = Instance.new("TextButton")
CamlockPartTorsoButton.Name = "CamlockPartTorsoButton"
CamlockPartTorsoButton.Parent = CamlockPartFrame
CamlockPartTorsoButton.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
CamlockPartTorsoButton.BorderColor3 = Color3.fromRGB(0, 0, 0)
CamlockPartTorsoButton.BorderSizePixel = 0
CamlockPartTorsoButton.Position = UDim2.new(0.0149999997, 0, 0.234999999, 0)
CamlockPartTorsoButton.Size = UDim2.new(0, 188, 0, 22)
CamlockPartTorsoButton.Font = Enum.Font.Highway
CamlockPartTorsoButton.Text = "Torso"
CamlockPartTorsoButton.TextColor3 = Color3.fromRGB(140, 140, 140)
CamlockPartTorsoButton.TextSize = 15.000

local CamlockPartHumanoidRootPartButton = Instance.new("TextButton")
CamlockPartHumanoidRootPartButton.Name = "CamlockPartHumanoidRootPartButton"
CamlockPartHumanoidRootPartButton.Parent = CamlockPartFrame
CamlockPartHumanoidRootPartButton.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
CamlockPartHumanoidRootPartButton.BorderColor3 = Color3.fromRGB(0, 0, 0)
CamlockPartHumanoidRootPartButton.BorderSizePixel = 0
CamlockPartHumanoidRootPartButton.Position = UDim2.new(0.0151448986, 0, 0.418827564, 0)
CamlockPartHumanoidRootPartButton.Size = UDim2.new(0, 188, 0, 22)
CamlockPartHumanoidRootPartButton.Font = Enum.Font.Highway
CamlockPartHumanoidRootPartButton.Text = "HumanoidRootPart"
CamlockPartHumanoidRootPartButton.TextColor3 = Color3.fromRGB(255, 255, 255)
CamlockPartHumanoidRootPartButton.TextSize = 15.000

local CamlockPartUpperTorsoButton = Instance.new("TextButton")
CamlockPartUpperTorsoButton.Name = "CamlockPartUpperTorsoButton"
CamlockPartUpperTorsoButton.Parent = CamlockPartFrame
CamlockPartUpperTorsoButton.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
CamlockPartUpperTorsoButton.BorderColor3 = Color3.fromRGB(0, 0, 0)
CamlockPartUpperTorsoButton.BorderSizePixel = 0
CamlockPartUpperTorsoButton.Position = UDim2.new(0.0149999997, 0, 0.605000019, 0)
CamlockPartUpperTorsoButton.Size = UDim2.new(0, 188, 0, 22)
CamlockPartUpperTorsoButton.Font = Enum.Font.Highway
CamlockPartUpperTorsoButton.Text = "UpperTorso"
CamlockPartUpperTorsoButton.TextColor3 = Color3.fromRGB(50, 50, 50)
CamlockPartUpperTorsoButton.TextSize = 15.000

local CamlockPartLowerTorsoButton = Instance.new("TextButton")
CamlockPartLowerTorsoButton.Name = "CamlockPartLowerTorsoButton"
CamlockPartLowerTorsoButton.Parent = CamlockPartFrame
CamlockPartLowerTorsoButton.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
CamlockPartLowerTorsoButton.BorderColor3 = Color3.fromRGB(0, 0, 0)
CamlockPartLowerTorsoButton.BorderSizePixel = 0
CamlockPartLowerTorsoButton.Position = UDim2.new(0.0149999997, 0, 0.790000021, 0)
CamlockPartLowerTorsoButton.Size = UDim2.new(0, 188, 0, 22)
CamlockPartLowerTorsoButton.Font = Enum.Font.Highway
CamlockPartLowerTorsoButton.Text = "LowerTorso"
CamlockPartLowerTorsoButton.TextColor3 = Color3.fromRGB(50, 50, 50)
CamlockPartLowerTorsoButton.TextSize = 15.000

local CamlockToggle = Instance.new("TextButton")
CamlockToggle.Name = "CamlockToggle"
CamlockToggle.Parent = CamlockFrame
CamlockToggle.BackgroundColor3 = Color3.fromRGB(15, 15, 15)
CamlockToggle.BorderColor3 = Color3.fromRGB(255, 255, 255)
CamlockToggle.BorderSizePixel = 2
CamlockToggle.Position = UDim2.new(0.0859725773, 0, 0.141176477, 0)
CamlockToggle.Size = UDim2.new(0, 14, 0, 14)
CamlockToggle.Font = Enum.Font.Highway
CamlockToggle.Text = "X"
CamlockToggle.TextColor3 = Color3.fromRGB(255, 255, 255)
CamlockToggle.TextSize = 14.000

local CamlockToggleLabel = Instance.new("TextLabel")
CamlockToggleLabel.Name = "CamlockToggleLabel"
CamlockToggleLabel.Parent = CamlockToggle
CamlockToggleLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
CamlockToggleLabel.BackgroundTransparency = 1.000
CamlockToggleLabel.BorderColor3 = Color3.fromRGB(0, 0, 0)
CamlockToggleLabel.BorderSizePixel = 0
CamlockToggleLabel.Position = UDim2.new(1.5, 0, 0, 0)
CamlockToggleLabel.Size = UDim2.new(0, 58, 0, 14)
CamlockToggleLabel.Font = Enum.Font.Highway
CamlockToggleLabel.Text = " - Camlock"
CamlockToggleLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
CamlockToggleLabel.TextSize = 14.000

local CamlockHotkeyTextBox = Instance.new("TextBox")
CamlockHotkeyTextBox.Name = "CamlockHotkeyTextBox"
CamlockHotkeyTextBox.Parent = CamlockFrame
CamlockHotkeyTextBox.BackgroundColor3 = Color3.fromRGB(15, 15, 15)
CamlockHotkeyTextBox.BorderColor3 = Color3.fromRGB(255, 255, 255)
CamlockHotkeyTextBox.BorderSizePixel = 2
CamlockHotkeyTextBox.Position = UDim2.new(0.583710134, 0, 0.141176477, 0)
CamlockHotkeyTextBox.Size = UDim2.new(0, 14, 0, 14)
CamlockHotkeyTextBox.Font = Enum.Font.Highway
CamlockHotkeyTextBox.PlaceholderColor3 = Color3.fromRGB(255, 255, 255)
CamlockHotkeyTextBox.PlaceholderText = "C"
CamlockHotkeyTextBox.Text = ""
CamlockHotkeyTextBox.TextColor3 = Color3.fromRGB(255, 255, 255)
CamlockHotkeyTextBox.TextSize = 14.000

local CamlockHotkeyLabel = Instance.new("TextLabel")
CamlockHotkeyLabel.Name = "CamlockHotkeyLabel"
CamlockHotkeyLabel.Parent = CamlockHotkeyTextBox
CamlockHotkeyLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
CamlockHotkeyLabel.BackgroundTransparency = 1.000
CamlockHotkeyLabel.BorderColor3 = Color3.fromRGB(0, 0, 0)
CamlockHotkeyLabel.BorderSizePixel = 0
CamlockHotkeyLabel.Position = UDim2.new(1.14285719, 0, 0, 0)
CamlockHotkeyLabel.Size = UDim2.new(0, 58, 0, 14)
CamlockHotkeyLabel.Font = Enum.Font.Highway
CamlockHotkeyLabel.Text = " - Hotkey"
CamlockHotkeyLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
CamlockHotkeyLabel.TextSize = 14.000

local CombatScrollingFrame2 = Instance.new("ScrollingFrame")
CombatScrollingFrame2.Name = "CombatScrollingFrame2"
CombatScrollingFrame2.Parent = MainFrame
CombatScrollingFrame2.Active = true
CombatScrollingFrame2.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
CombatScrollingFrame2.BorderColor3 = Color3.fromRGB(0, 0, 0)
CombatScrollingFrame2.BorderSizePixel = 0
CombatScrollingFrame2.Position = UDim2.new(0.5, 0, 0.0509666093, 0)
CombatScrollingFrame2.Size = UDim2.new(0, 229, 0, 540)
CombatScrollingFrame2.ScrollBarThickness = 4
